const GAME_DATA = {
  1: {
    moneyCollected: 190,
    playedAt: "7/18/2020, 10:43:05 PM",
    gameData: {
      titlesAndPrizes: {
        _jaldi_5: 19,
        _1st_line: 28.5,
        _2nd_line: 28.5,
        _3rd_line: 28.5,
        _housefull_1: 47.5,
        _housefull_2: 38,
      },
      winners: [
        "Praharsh",
        "Vidhathri",
        "Vidhathri",
        "Rajamannar",
        "Sumedh",
        "Anuhya",
      ],
    },
  },
  2: {
    moneyCollected: 230,
    playedAt: "7/18/2020, 11:16:12 PM",
    gameData: {
      titlesAndPrizes: {
        _jaldi_5: 23,
        _1st_line: 34.5,
        _2nd_line: 34.5,
        _3rd_line: 34.5,
        _housefull_1: 57.5,
        _housefull_2: 46,
      },
      winners: [
        "Aaruhya",
        "Anuhya",
        "Anuhya",
        "Aaruhya",
        "Aaradhya",
        "Subba Rao",
      ],
    },
  },
  3: {
    moneyCollected: 230,
    playedAt: "7/18/2020, 11:31:36 PM",
    gameData: {
      titlesAndPrizes: {
        _jaldi_5: 23,
        _1st_line: 34.5,
        _2nd_line: 34.5,
        _3rd_line: 34.5,
        _housefull_1: 57.5,
        _housefull_2: 46,
      },
      winners: [
        "Ammamma",
        "Vidhathri",
        "Obul Reddy",
        "Obul Reddy",
        "Obul Reddy",
        "Sumedh",
      ],
    },
  },
  4: {
    moneyCollected: 230,
    playedAt: "7/18/2020, 11:46:56 PM",
    gameData: {
      titlesAndPrizes: {
        _jaldi_5: 23,
        _1st_line: 34.5,
        _2nd_line: 34.5,
        _3rd_line: 34.5,
        _housefull_1: 57.5,
        _housefull_2: 46,
      },
      winners: [
        "Sriram",
        "Vidhathri",
        "Rajamannar",
        "Sumedh",
        "Subba Rao",
        "Vidhathri",
      ],
    },
  },
  5: {
    moneyCollected: 240,
    playedAt: "7/19/2020, 05:57:22 PM",
    gameData: {
      titlesAndPrizes: {
        _jaldi_5: 24,
        _1st_line: 36,
        _2nd_line: 36,
        _3rd_line: 36,
        _housefull_1: 60,
        _housefull_2: 48,
      },
      winners: [
        "Ammamma",
        "Ammamma",
        "Ammamma",
        "Obul Reddy",
        "Ammamma",
        "Madhavi",
      ],
    },
  },
  6: {
    moneyCollected: 220,
    playedAt: "7/19/2020, 06:10:07 PM",
    gameData: {
      titlesAndPrizes: {
        _jaldi_5: 22,
        _1st_line: 33,
        _2nd_line: 33,
        _3rd_line: 33,
        _housefull_1: 55,
        _housefull_2: 44,
      },
      winners: [
        "Sumedh",
        "Sumedh",
        "Sumaukthi",
        "Obul Reddy & Rajamannar",
        "Rajamannar",
        "Manasvini",
      ],
    },
  },
  7: {
    moneyCollected: 220,
    playedAt: "7/19/2020, 06:32:46 PM",
    gameData: {
      titlesAndPrizes: {
        _jaldi_5: 22,
        _1st_line: 33,
        _2nd_line: 33,
        _3rd_line: 33,
        _housefull_1: 55,
        _housefull_2: 44,
      },
      winners: [
        "Rajamannar",
        "Rajamannar",
        "Rajamannar",
        "Svanik",
        "Rajamannar",
        "Obul Reddy",
      ],
    },
  },
  8: {
    moneyCollected: 250,
    playedAt: "7/19/2020, 07:00:12 PM",
    gameData: {
      titlesAndPrizes: {
        _jaldi_5: 25,
        _1st_line: 37.5,
        _2nd_line: 37.5,
        _3rd_line: 37.5,
        _housefull_1: 62.5,
        _housefull_2: 50,
      },
      winners: [
        "Sriram",
        "Sumedh",
        "Rama & Aaradhya",
        "Sriram",
        "Sumaukthi",
        "Rajamannar",
      ],
    },
  },
  9: {
    moneyCollected: 240,
    playedAt: "7/19/2020, 07:23:31 PM",
    gameData: {
      titlesAndPrizes: {
        _jaldi_5: 24,
        _1st_line: 36,
        _2nd_line: 36,
        _3rd_line: 36,
        _housefull_1: 60,
        _housefull_2: 48,
      },
      winners: [
        "Obul Reddy",
        "Sumaukthi",
        "Obul Reddy & Sriram",
        "Aaruhya",
        "Sumaukthi",
        "Vidhathri & Anuhya",
      ],
    },
  },
  10: {
    moneyCollected: 240,
    playedAt: "7/19/2020, 07:47:24 PM",
    gameData: {
      titlesAndPrizes: {
        _jaldi_5: 24,
        _1st_line: 36,
        _2nd_line: 36,
        _3rd_line: 36,
        _housefull_1: 60,
        _housefull_2: 48,
      },
      winners: [
        "Madhavi",
        "Anuhya",
        "Manasvini",
        "Sumedh",
        "Ammamma",
        "Rajamannar",
      ],
    },
  },
  11: {
    moneyCollected: 240,
    playedAt: "7/20/2020, 09:57:10 PM",
    gameData: {
      titlesAndPrizes: {
        _jaldi_5: 24,
        _1st_line: 36,
        _2nd_line: 36,
        _3rd_line: 36,
        _housefull_1: 60,
        _housefull_2: 48,
      },
      winners: [
        "Vijay Rama Rao",
        "Rajamannar",
        "Svanik",
        "Vidhathri",
        "Svanik",
        "Aaruhya",
      ],
    },
  },
  12: {
    moneyCollected: 260,
    playedAt: "7/20/2020, 10:10:01 PM",
    gameData: {
      titlesAndPrizes: {
        _jaldi_5: 26,
        _1st_line: 39,
        _2nd_line: 39,
        _3rd_line: 39,
        _housefull_1: 65,
        _housefull_2: 52,
      },
      winners: [
        "Obul Reddy",
        "Madhavi",
        "Anuhya",
        "Vijay Rama Rao",
        "Rajamannar",
        "Vidhathri & Rama",
      ],
    },
  },
  13: {
    moneyCollected: 250,
    playedAt: "7/20/2020, 10:24:13 PM",
    gameData: {
      titlesAndPrizes: {
        _jaldi_5: 25,
        _1st_line: 37.5,
        _2nd_line: 37.5,
        _3rd_line: 37.5,
        _housefull_1: 62.5,
        _housefull_2: 50,
      },
      winners: [
        "Sakuntala",
        "Madhavi",
        "Aaruhya",
        "Manasvini",
        "Madhavi",
        "Subba Rao",
      ],
    },
  },
  14: {
    moneyCollected: 250,
    playedAt: "7/20/2020, 10:38:27 PM",
    gameData: {
      titlesAndPrizes: {
        _jaldi_5: 25,
        _1st_line: 37.5,
        _2nd_line: 37.5,
        _3rd_line: 37.5,
        _housefull_1: 62.5,
        _housefull_2: 50,
      },
      winners: [
        "Madhavi",
        "Rama",
        "Vijay Rama Rao & Svanik",
        "Sumaukthi",
        "Vidhathri",
        "Rama",
      ],
    },
  },
};

export default GAME_DATA;
